export LD_LIBRARY_PATH="/opt/sqlite/sqlite3/lib"
export LD_LIBRARY_PATH="/opt/sqlite/sqlite3/lib"
export LD_LIBRARY_PATH="/opt/sqlite/sqlite3/lib"
export LD_LIBRARY_PATH="/opt/sqlite/sqlite3/lib"
export LD_LIBRARY_PATH="/opt/sqlite/sqlite3/lib"
export LD_LIBRARY_PATH="/usr/local/bin/sqlite3/lib"
export LD_LIBRARY_PATH="/opt/sqlite/sqlite3/lib"
